cargo-features = ["profile-rustflags"]

[package]
name = "blart"
version = "0.1.2"
description = "An implementation of an adaptive radix tree packaged as a BTreeMap replacement"
repository = "https://github.com/declanvk/blart"
readme = "README.md"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["tree", "map", "collection", "radix-tree"]
categories = ["data-structures"]

exclude = [
    "fuzz/",
    "scripts/",
    "rustfmt.toml",
    "examples/example-data/",
    ".github/",
]

[dependencies]
sptr = "0.3.2"
tinyvec = { version = "1.6.0", features = ["std", "rustc_1_57"] }
bytemuck = { version = "1.14.0", features = ["min_const_generics"] }

[features]
nightly = []

[dev-dependencies]
argh = "0.1.12"
criterion = "0.5.1"
dhat = "0.3.2"
rustc-hash = "1.1.0"
paste = "1.0.14"
criterion-perf-events = "0.4.0"
perfcnt = "0.8.0"

[[bench]]
name = "generated_get"
harness = false

[[bench]]
name = "generated_insert"
harness = false

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
incremental = false
rustflags = ["-C", "target-cpu=native", "-Z", "tune-cpu=native"]