cargo-features = ["profile-rustflags"]

[package]
name = "blart"
version = "0.1.2"
description = "An implementation of an adaptive radix tree packaged as a BTreeMap replacement"
repository = "https://github.com/declanvk/blart"
readme = "README.md"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["tree", "map", "collection", "radix-tree"]
categories = ["data-structures"]

exclude = [
    "fuzz/",
    "scripts/",
    "rustfmt.toml",
    "examples/example-data/",
    ".github/",
]

[dependencies]
sptr = "0.3.2"
bytemuck = { version = "1.14.0", features = ["min_const_generics"] }

[features]
nightly = []
perf-events = []
gen-benches-macro = []

[dev-dependencies]
argh = "0.1.12"
criterion = "0.5.1"
dhat = "0.3.2"
rustc-hash = "1.1.0"
paste = "1.0.14"
criterion-perf-events = "0.4.0"
perfcnt = "0.8.0"
rand = "0.8.5"

[[bench]]
name = "generated_get"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "generated_insert"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "dict_insert"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "get_fuzzy"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "dict_get"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "min_max"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "match_prefix"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "entry"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "iter"
harness = false
required-features = ["gen-benches-macro"]

[[bench]]
name = "clone"
harness = false
required-features = ["gen-benches-macro"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
incremental = false
rustflags = ["-C", "target-cpu=native", "-Z", "tune-cpu=native"]